### PR TITLE
Add contributor

### PR DESCRIPTION
**Pull request by thedammyking**
Adding myself to the contributors list

### CODE REVIEW

**Comment by celesteessel** [comment]
How do I make a pull request?

**Comment by AliceWonderland** [comment]
Please update your fork with master. Then re-open this PR or create a new one!

**Comment by celesteessel** [comment]
Okay thank you! I made a new one

**Comment by Roshanjossey** [comment]
Hi  @thedammyking, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

**Pull request closed without merging**
