### PR TITLE
Added new contributor, dale

### PR DESCRIPTION
**Pull request by dalenoe**
my first PR, hopefully it gets merged.

### CODE REVIEW

**Comment by dalenoe** [comment]
Just 1 review left, lol..

**Comment by StevenCopeland** [comment]
@dalenoe  Congrats on your first PR!

**Comment by dalenoe** [comment]
Thanks @StevenCopeland

**Comment by StevenCopeland** [comment]
Anytime @dalenoe!

**Comment by Roshanjossey** [comment]
Hi  @dalenoe, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

**Pull request merged**
