### PR TITLE
Added my name

### PR DESCRIPTION
**Pull request by price84**

### CODE REVIEW

**Review by AliceWonderland — CHANGES_REQUESTED** [review]
Hello! I am unable to resolve merge conflicts in your file! Please add or allow this repo to edit yours!

**Review by AliceWonderland — APPROVED** [review]
Test

**Review by AliceWonderland — CHANGES_REQUESTED** [review]
Test

**Comment by Roshanjossey** [comment]
Hi  @price84, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

**Pull request closed without merging**
