### PR TITLE
Adding myself to CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by dan1eltudares**
Adding my name, place and link to CONTRIBUTORS.md

### CODE REVIEW

**Comment by dan1eltudares** [comment]
Why everyone keeps adding stuff after me and my PR is not approved? Am I missing an step? I have resolve conflicts 2 times now.

**Comment by StevenCopeland** [comment]
@dan1eltudares As you can see there are a lot of PRs and it is hard to marge each new one as they come in. I can understand your frustration, but there is a lot to do.

**Comment by dan1eltudares** [comment]
Thanks a lot Steven! This wasn't an angry complainment, it was more like a "Am I'm doing it right?" kind of question since this is my first official PR pulled on a public repo! Wasn't sure if I was missing a step here :) Again, thanks a lot and cheers!

**Comment by StevenCopeland** [comment]
@dan1eltudares Okay. Sorry! I should not have jumped to conclusions. Happy Hacktoberfest! :jack_o_lantern:

**Comment by Roshanjossey** [comment]
Hi  @dan1eltudares, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

**Pull request merged**
