### PR TITLE
Final Hacktoberfest PR

### PR DESCRIPTION
**Pull request by aesherman**
This.

### CODE REVIEW

**Comment by Roshanjossey** [comment]
Hi  @aesherman, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

**Comment by jayegri** [comment]
Update index.html

**Comment by europateam** [comment]
hacktoberfest update

**Comment by viniciusfdasilva** [comment]
update

**Pull request closed without merging**
