### PR TITLE
Create HelloWorld.ml

### PR DESCRIPTION
**Pull request by adi0602**
Hello World in Objective caml (Ocaml)

### CODE REVIEW

**Comment by adi0602** [comment]
There are 4 more pull requests to create 4 more files that I've submitted 2
days ago.
I request you to please have a look at them and it will be very helpful to
receive your feedback on why they are not yet merged with main branch.
Thank you.

**Comment by StevenCopeland** [comment]
@adi0602 Will please tell me what number they are?

**Comment by adi0602** [comment]
#1405
#1463
#1464
#1468
#1470 (contributers.md)

**Comment by StevenCopeland** [comment]
@adi0602 Merged most of them to master

**Comment by Roshanjossey** [comment]
Hi  @adi0602, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

**Pull request merged**
