### PR TITLE
Joseph Banks

### PR DESCRIPTION
**Pull request by jb3**

### CODE REVIEW

**Review by AliceWonderland — CHANGES_REQUESTED** [review]
Hello! Could you add comments to your script file to include the language you're using (and your name as the author if you'd like)?

Thanks!

**Comment by JoeBanks13** [comment]
Updated script files :smile:

**Review by AliceWonderland — APPROVED** [review]
Hello! Sorry for the delay. Thanks for making those changes :) And Happy Hacktoberfest!

**Comment by Roshanjossey** [comment]
Hi  @JoeBanks13, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

**Comment by JoeBanks13** [comment]
That's great to hear but I already have done hacktoberfest and I wanted the fancy T-shirt. I'll take a look but I already contribute to a number of projects on GitHub.

**Pull request merged**
