### PR TITLE
added tjboller

### PR DESCRIPTION
**Pull request by tjboller**
This was helpful thanks!

### CODE REVIEW

**Comment by StevenCopeland** [comment]
@tjboller Congrats on your first PR!

**Comment by StevenCopeland** [comment]
Also, Do you watch baseball?

**Comment by tjboller** [comment]
thanks steve! Good idea with the project it was really helpful. And haha no
i don't, why do you ask?

**Comment by StevenCopeland** [comment]
@tjboller Because you are from Boston(I assume US) and the Boston Red Soxs are rivals of the New York Yankees(my team).

**Comment by tjboller** [comment]
Ah lol no I moved here for grad school. I grew up in the NY area - my
family is Met's fan. Yanks looking good tho! Good luck

**Comment by Roshanjossey** [comment]
Hi  @tjboller, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

**Pull request merged**
