### PR TITLE
Add contributor

### PR DESCRIPTION
**Pull request by nusendra**
#### Name: [YOUR NAME](GitHub Link)
  - Place: Gresik, East Java, Indonesia
  - Bio: Web App Developer, Desktop App Dev and Network Engineer
  - GitHub: [Nusendra](https://github.com/andraeinstein)

### CODE REVIEW

**Comment by krishnatandon1208** [comment]
Name: KRISHNA TANDON

Place: Pune, India
Bio: Web App Developer
GitHub: krishnatandon1208

**Comment by shashanksi2009** [comment]
Name: Shashank Singh
Bio: Web App Developer
Github: shashanksi2009@gmail.com

**Review by shashanksi2009 — APPROVED** [review]

**Review by shashanksi2009 — APPROVED** [review]
Approved

**Comment by Roshanjossey** [comment]
Hi  @nusendra, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

**Comment by nusendra** [comment]
@Roshanjossey cool

**Comment by asotronot** [comment]
Name: Ahmet Oguz
Place: Salt Lake City, Utah
Bio: Software Engineer
Github: [asotronot] (https://github.com/asotronot)

**Comment by Mastermind63** [comment]
Name: Man
Bio: I have an ammount of gold *mumbles under breath "I said to much"
Place: Earth
github: [Mastermind63] https://github.com/Mastermind63

**Comment by Yudhst** [comment]
Name: [Naufal Yudhistira](https://github.com/Yudhst)

    Place: Malang, Indonesia
    Bio: Student
    GitHub: https://github.com/Yudhst

**Comment by danagibson** [comment]
Name: Dana Gibson
Bio: Retired and trying to keep busy.
Place: San Diego, California
github: https://github.com/danagibson

**Pull request closed without merging**
