### PR TITLE
hacktober fest contribution

### PR DESCRIPTION
**Pull request by Nefari0uss**

### CODE REVIEW

**Comment by Nefari0uss** [comment]
Sure thing! I'll do it tonight.

**Comment by Nefari0uss** [comment]
@AliceWonderland Updated with changes as requested. Please review.

**Comment by Nefari0uss** [comment]
Gentle bump. @AliceWonderland

**Comment by Roshanjossey** [comment]
Hi  @Nefari0uss, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

**Pull request merged**
