### PR TITLE
Resolved

### PR DESCRIPTION
**Pull request by jarvis8**

### CODE REVIEW

**Comment by jarvis8** [comment]
Please Merge

**Comment by jarvis8** [comment]
@AliceWonderland
 Interested in being a collaborator.

**Review by AmitDave22 — APPROVED** [review]
Could you also review my pull request?
https://github.com/AmitDave22/hacktoberfest/pull/new/new_branch

**Review by AmitDave22 — APPROVED** [review]

**Comment by jarvis8** [comment]
Done

**Pull request closed without merging**
