### PR TITLE
Created Hello World

### PR DESCRIPTION
**Pull request by AlexandreVelloso**

### CODE REVIEW

**Comment by senpai-shuja** [comment]
fixed

**Comment by PriyaPal-tech** [comment]
created hello world

**Comment by JametKuy** [comment]
hello world

**Comment by BlackHat-TG** [comment]
hello world
`print("hello world")`

**Comment by FikriEl** [comment]
hello world
print("hello world")

**Comment by priyavatsya** [comment]
print('hello world')

**Comment by kavisha-nethmini** [comment]
class HelloWorld 
{ 

	public static void main(String args[]) 
	{ 
		System.out.println("Hello, World"); 
	} 
}

**Comment by sophiebby** [comment]
Hello world

**Comment by AlexandreEXTREMAO** [comment]
print("Hello World")

**Comment by ishistarx** [comment]
print("Hello World")

**Comment by chm0d7** [comment]
print("Hello World!)

**Comment by kulkarni-laxmi** [comment]
print("HELLOE WORLD!)

**Comment by Alensheen** [comment]
print("hello world!")

**Pull request closed without merging**
